(cl:defpackage micros_swarm_framework-srv
  (:use )
  (:export
   "APPLOAD"
   "<APPLOAD-REQUEST>"
   "APPLOAD-REQUEST"
   "<APPLOAD-RESPONSE>"
   "APPLOAD-RESPONSE"
   "APPUNLOAD"
   "<APPUNLOAD-REQUEST>"
   "APPUNLOAD-REQUEST"
   "<APPUNLOAD-RESPONSE>"
   "APPUNLOAD-RESPONSE"
   "RTPDESTROY"
   "<RTPDESTROY-REQUEST>"
   "RTPDESTROY-REQUEST"
   "<RTPDESTROY-RESPONSE>"
   "RTPDESTROY-RESPONSE"
  ))

