// Generated by gencpp from file micros_swarm_framework/AppLoad.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOAD_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOAD_H

#include <ros/service_traits.h>


#include <micros_swarm_framework/AppLoadRequest.h>
#include <micros_swarm_framework/AppLoadResponse.h>


namespace micros_swarm_framework
{

struct AppLoad
{

typedef AppLoadRequest Request;
typedef AppLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AppLoad
} // namespace micros_swarm_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micros_swarm_framework::AppLoad > {
  static const char* value()
  {
    return "9e491318c68b9fbf00509a80adfec2ec";
  }

  static const char* value(const ::micros_swarm_framework::AppLoad&) { return value(); }
};

template<>
struct DataType< ::micros_swarm_framework::AppLoad > {
  static const char* value()
  {
    return "micros_swarm_framework/AppLoad";
  }

  static const char* value(const ::micros_swarm_framework::AppLoad&) { return value(); }
};


// service_traits::MD5Sum< ::micros_swarm_framework::AppLoadRequest> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::AppLoad > 
template<>
struct MD5Sum< ::micros_swarm_framework::AppLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::AppLoad >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::AppLoadRequest> should match 
// service_traits::DataType< ::micros_swarm_framework::AppLoad > 
template<>
struct DataType< ::micros_swarm_framework::AppLoadRequest>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::AppLoad >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micros_swarm_framework::AppLoadResponse> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::AppLoad > 
template<>
struct MD5Sum< ::micros_swarm_framework::AppLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::AppLoad >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::AppLoadResponse> should match 
// service_traits::DataType< ::micros_swarm_framework::AppLoad > 
template<>
struct DataType< ::micros_swarm_framework::AppLoadResponse>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::AppLoad >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOAD_H
