// Generated by gencpp from file micros_swarm_framework/AppLoadResponse.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOADRESPONSE_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micros_swarm_framework
{
template <class ContainerAllocator>
struct AppLoadResponse_
{
  typedef AppLoadResponse_<ContainerAllocator> Type;

  AppLoadResponse_()
    : success(false)  {
    }
  AppLoadResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AppLoadResponse_

typedef ::micros_swarm_framework::AppLoadResponse_<std::allocator<void> > AppLoadResponse;

typedef boost::shared_ptr< ::micros_swarm_framework::AppLoadResponse > AppLoadResponsePtr;
typedef boost::shared_ptr< ::micros_swarm_framework::AppLoadResponse const> AppLoadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace micros_swarm_framework

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'micros_swarm_framework': ['/home/bas/catkin_ws_multirob/src/micros_swarm_framework/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micros_swarm_framework/AppLoadResponse";
  }

  static const char* value(const ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AppLoadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micros_swarm_framework::AppLoadResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_APPLOADRESPONSE_H
