// Generated by gencpp from file micros_swarm_framework/AppUnloadRequest.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOADREQUEST_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micros_swarm_framework
{
template <class ContainerAllocator>
struct AppUnloadRequest_
{
  typedef AppUnloadRequest_<ContainerAllocator> Type;

  AppUnloadRequest_()
    : name()
    , type()  {
    }
  AppUnloadRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AppUnloadRequest_

typedef ::micros_swarm_framework::AppUnloadRequest_<std::allocator<void> > AppUnloadRequest;

typedef boost::shared_ptr< ::micros_swarm_framework::AppUnloadRequest > AppUnloadRequestPtr;
typedef boost::shared_ptr< ::micros_swarm_framework::AppUnloadRequest const> AppUnloadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace micros_swarm_framework

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'micros_swarm_framework': ['/home/bas/catkin_ws_multirob/src/micros_swarm_framework/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f11915b22b276d2fb5587b35400289d";
  }

  static const char* value(const ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f11915b22b276d2ULL;
  static const uint64_t static_value2 = 0xfb5587b35400289dULL;
};

template<class ContainerAllocator>
struct DataType< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micros_swarm_framework/AppUnloadRequest";
  }

  static const char* value(const ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string type\n\
";
  }

  static const char* value(const ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AppUnloadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micros_swarm_framework::AppUnloadRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOADREQUEST_H
