// Generated by gencpp from file micros_swarm_framework/AppUnload.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOAD_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOAD_H

#include <ros/service_traits.h>


#include <micros_swarm_framework/AppUnloadRequest.h>
#include <micros_swarm_framework/AppUnloadResponse.h>


namespace micros_swarm_framework
{

struct AppUnload
{

typedef AppUnloadRequest Request;
typedef AppUnloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AppUnload
} // namespace micros_swarm_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micros_swarm_framework::AppUnload > {
  static const char* value()
  {
    return "9e491318c68b9fbf00509a80adfec2ec";
  }

  static const char* value(const ::micros_swarm_framework::AppUnload&) { return value(); }
};

template<>
struct DataType< ::micros_swarm_framework::AppUnload > {
  static const char* value()
  {
    return "micros_swarm_framework/AppUnload";
  }

  static const char* value(const ::micros_swarm_framework::AppUnload&) { return value(); }
};


// service_traits::MD5Sum< ::micros_swarm_framework::AppUnloadRequest> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::AppUnload > 
template<>
struct MD5Sum< ::micros_swarm_framework::AppUnloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::AppUnload >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppUnloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::AppUnloadRequest> should match 
// service_traits::DataType< ::micros_swarm_framework::AppUnload > 
template<>
struct DataType< ::micros_swarm_framework::AppUnloadRequest>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::AppUnload >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppUnloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micros_swarm_framework::AppUnloadResponse> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::AppUnload > 
template<>
struct MD5Sum< ::micros_swarm_framework::AppUnloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::AppUnload >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppUnloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::AppUnloadResponse> should match 
// service_traits::DataType< ::micros_swarm_framework::AppUnload > 
template<>
struct DataType< ::micros_swarm_framework::AppUnloadResponse>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::AppUnload >::value();
  }
  static const char* value(const ::micros_swarm_framework::AppUnloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_APPUNLOAD_H
