// Generated by gencpp from file micros_swarm_framework/RTPDestroy.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROY_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROY_H

#include <ros/service_traits.h>


#include <micros_swarm_framework/RTPDestroyRequest.h>
#include <micros_swarm_framework/RTPDestroyResponse.h>


namespace micros_swarm_framework
{

struct RTPDestroy
{

typedef RTPDestroyRequest Request;
typedef RTPDestroyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTPDestroy
} // namespace micros_swarm_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micros_swarm_framework::RTPDestroy > {
  static const char* value()
  {
    return "36405beac40f6723e71d2520ae768ec2";
  }

  static const char* value(const ::micros_swarm_framework::RTPDestroy&) { return value(); }
};

template<>
struct DataType< ::micros_swarm_framework::RTPDestroy > {
  static const char* value()
  {
    return "micros_swarm_framework/RTPDestroy";
  }

  static const char* value(const ::micros_swarm_framework::RTPDestroy&) { return value(); }
};


// service_traits::MD5Sum< ::micros_swarm_framework::RTPDestroyRequest> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::RTPDestroy > 
template<>
struct MD5Sum< ::micros_swarm_framework::RTPDestroyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::RTPDestroy >::value();
  }
  static const char* value(const ::micros_swarm_framework::RTPDestroyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::RTPDestroyRequest> should match 
// service_traits::DataType< ::micros_swarm_framework::RTPDestroy > 
template<>
struct DataType< ::micros_swarm_framework::RTPDestroyRequest>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::RTPDestroy >::value();
  }
  static const char* value(const ::micros_swarm_framework::RTPDestroyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micros_swarm_framework::RTPDestroyResponse> should match 
// service_traits::MD5Sum< ::micros_swarm_framework::RTPDestroy > 
template<>
struct MD5Sum< ::micros_swarm_framework::RTPDestroyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micros_swarm_framework::RTPDestroy >::value();
  }
  static const char* value(const ::micros_swarm_framework::RTPDestroyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micros_swarm_framework::RTPDestroyResponse> should match 
// service_traits::DataType< ::micros_swarm_framework::RTPDestroy > 
template<>
struct DataType< ::micros_swarm_framework::RTPDestroyResponse>
{
  static const char* value()
  {
    return DataType< ::micros_swarm_framework::RTPDestroy >::value();
  }
  static const char* value(const ::micros_swarm_framework::RTPDestroyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROY_H
