// Generated by gencpp from file micros_swarm_framework/RTPDestroyRequest.msg
// DO NOT EDIT!


#ifndef MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROYREQUEST_H
#define MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micros_swarm_framework
{
template <class ContainerAllocator>
struct RTPDestroyRequest_
{
  typedef RTPDestroyRequest_<ContainerAllocator> Type;

  RTPDestroyRequest_()
    : code(0)  {
    }
  RTPDestroyRequest_(const ContainerAllocator& _alloc)
    : code(0)  {
  (void)_alloc;
    }



   typedef int8_t _code_type;
  _code_type code;




  typedef boost::shared_ptr< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RTPDestroyRequest_

typedef ::micros_swarm_framework::RTPDestroyRequest_<std::allocator<void> > RTPDestroyRequest;

typedef boost::shared_ptr< ::micros_swarm_framework::RTPDestroyRequest > RTPDestroyRequestPtr;
typedef boost::shared_ptr< ::micros_swarm_framework::RTPDestroyRequest const> RTPDestroyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace micros_swarm_framework

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'micros_swarm_framework': ['/home/bas/catkin_ws_multirob/src/micros_swarm_framework/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95cfa23476470f3d4705c11337b96909";
  }

  static const char* value(const ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95cfa23476470f3dULL;
  static const uint64_t static_value2 = 0x4705c11337b96909ULL;
};

template<class ContainerAllocator>
struct DataType< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micros_swarm_framework/RTPDestroyRequest";
  }

  static const char* value(const ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 code\n\
";
  }

  static const char* value(const ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTPDestroyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micros_swarm_framework::RTPDestroyRequest_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROS_SWARM_FRAMEWORK_MESSAGE_RTPDESTROYREQUEST_H
